apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  template:
  labels:
    app: udagram-reverseproxy
  template:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: seece/udagram-reverseproxy
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
