apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: seece/udagram-api-user:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
